// automatically generated by the FlatBuffers compiler, do not modify

package Repos;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;
import io.flatbufferx.core.FlatBufferSrc;

@SuppressWarnings("unused")
@FlatBufferSrc
public final class User extends Table {
  public static User getRootAsUser(ByteBuffer _bb) { return getRootAsUser(_bb, new User()); }
  public static User getRootAsUser(ByteBuffer _bb, User obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public User __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String login() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer loginAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer loginInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long id() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String avatarUrl() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer avatarUrlAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer avatarUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String gravatarId() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer gravatarIdAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer gravatarIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String url() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer urlAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer urlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String htmlUrl() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer htmlUrlAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer htmlUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String followersUrl() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer followersUrlAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer followersUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String followingUrl() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer followingUrlAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer followingUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String gistsUrl() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer gistsUrlAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer gistsUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public String starredUrl() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer starredUrlAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public ByteBuffer starredUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 1); }
  public String subscriptionsUrl() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subscriptionsUrlAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer subscriptionsUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }
  public String organizationsUrl() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer organizationsUrlAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }
  public ByteBuffer organizationsUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 26, 1); }
  public String reposUrl() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reposUrlAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public ByteBuffer reposUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 28, 1); }
  public String eventsUrl() { int o = __offset(30); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventsUrlAsByteBuffer() { return __vector_as_bytebuffer(30, 1); }
  public ByteBuffer eventsUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 30, 1); }
  public String receivedEventsUrl() { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer receivedEventsUrlAsByteBuffer() { return __vector_as_bytebuffer(32, 1); }
  public ByteBuffer receivedEventsUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 32, 1); }
  public String type() { int o = __offset(34); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer typeAsByteBuffer() { return __vector_as_bytebuffer(34, 1); }
  public ByteBuffer typeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 34, 1); }
  public boolean siteAdmin() { int o = __offset(36); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createUser(FlatBufferBuilder builder,
      int loginOffset,
      long id,
      int avatar_urlOffset,
      int gravatar_idOffset,
      int urlOffset,
      int html_urlOffset,
      int followers_urlOffset,
      int following_urlOffset,
      int gists_urlOffset,
      int starred_urlOffset,
      int subscriptions_urlOffset,
      int organizations_urlOffset,
      int repos_urlOffset,
      int events_urlOffset,
      int received_events_urlOffset,
      int typeOffset,
      boolean site_admin) {
    builder.startObject(17);
    User.addId(builder, id);
    User.addType(builder, typeOffset);
    User.addReceivedEventsUrl(builder, received_events_urlOffset);
    User.addEventsUrl(builder, events_urlOffset);
    User.addReposUrl(builder, repos_urlOffset);
    User.addOrganizationsUrl(builder, organizations_urlOffset);
    User.addSubscriptionsUrl(builder, subscriptions_urlOffset);
    User.addStarredUrl(builder, starred_urlOffset);
    User.addGistsUrl(builder, gists_urlOffset);
    User.addFollowingUrl(builder, following_urlOffset);
    User.addFollowersUrl(builder, followers_urlOffset);
    User.addHtmlUrl(builder, html_urlOffset);
    User.addUrl(builder, urlOffset);
    User.addGravatarId(builder, gravatar_idOffset);
    User.addAvatarUrl(builder, avatar_urlOffset);
    User.addLogin(builder, loginOffset);
    User.addSiteAdmin(builder, site_admin);
    return User.endUser(builder);
  }

  public static void startUser(FlatBufferBuilder builder) { builder.startObject(17); }
  public static void addLogin(FlatBufferBuilder builder, int loginOffset) { builder.addOffset(0, loginOffset, 0); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(1, id, 0L); }
  public static void addAvatarUrl(FlatBufferBuilder builder, int avatarUrlOffset) { builder.addOffset(2, avatarUrlOffset, 0); }
  public static void addGravatarId(FlatBufferBuilder builder, int gravatarIdOffset) { builder.addOffset(3, gravatarIdOffset, 0); }
  public static void addUrl(FlatBufferBuilder builder, int urlOffset) { builder.addOffset(4, urlOffset, 0); }
  public static void addHtmlUrl(FlatBufferBuilder builder, int htmlUrlOffset) { builder.addOffset(5, htmlUrlOffset, 0); }
  public static void addFollowersUrl(FlatBufferBuilder builder, int followersUrlOffset) { builder.addOffset(6, followersUrlOffset, 0); }
  public static void addFollowingUrl(FlatBufferBuilder builder, int followingUrlOffset) { builder.addOffset(7, followingUrlOffset, 0); }
  public static void addGistsUrl(FlatBufferBuilder builder, int gistsUrlOffset) { builder.addOffset(8, gistsUrlOffset, 0); }
  public static void addStarredUrl(FlatBufferBuilder builder, int starredUrlOffset) { builder.addOffset(9, starredUrlOffset, 0); }
  public static void addSubscriptionsUrl(FlatBufferBuilder builder, int subscriptionsUrlOffset) { builder.addOffset(10, subscriptionsUrlOffset, 0); }
  public static void addOrganizationsUrl(FlatBufferBuilder builder, int organizationsUrlOffset) { builder.addOffset(11, organizationsUrlOffset, 0); }
  public static void addReposUrl(FlatBufferBuilder builder, int reposUrlOffset) { builder.addOffset(12, reposUrlOffset, 0); }
  public static void addEventsUrl(FlatBufferBuilder builder, int eventsUrlOffset) { builder.addOffset(13, eventsUrlOffset, 0); }
  public static void addReceivedEventsUrl(FlatBufferBuilder builder, int receivedEventsUrlOffset) { builder.addOffset(14, receivedEventsUrlOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(15, typeOffset, 0); }
  public static void addSiteAdmin(FlatBufferBuilder builder, boolean siteAdmin) { builder.addBoolean(16, siteAdmin, false); }
  public static int endUser(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

