// automatically generated by the FlatBuffers compiler, do not modify

package io.flatbutterx.sample;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Repo2 extends Table {
  public static Repo2 getRootAsRepo2(ByteBuffer _bb) { return getRootAsRepo2(_bb, new Repo2()); }
  public static Repo2 getRootAsRepo2(ByteBuffer _bb, Repo2 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Repo2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createRepo2(FlatBufferBuilder builder,
      long id,
      int nameOffset) {
    builder.startObject(2);
    Repo2.addId(builder, id);
    Repo2.addName(builder, nameOffset);
    return Repo2.endRepo2(builder);
  }

  public static void startRepo2(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static int endRepo2(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

