// automatically generated by the FlatBuffers compiler, do not modify

package io.flatbutterx.sample;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;
import io.flatbufferx.core.FlatBufferSrc;

@SuppressWarnings("unused")
@FlatBufferSrc
public final class Repo extends Table {
  public static Repo getRootAsRepo(ByteBuffer _bb) { return getRootAsRepo(_bb, new Repo()); }
  public static Repo getRootAsRepo(ByteBuffer _bb, Repo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Repo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String fullName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fullNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer fullNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public User owner() { return owner(new User()); }
  public User owner(User obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String htmlUrl() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer htmlUrlAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer htmlUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String description() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }

  public static int createRepo(FlatBufferBuilder builder,
      long id,
      int nameOffset,
      int full_nameOffset,
      int ownerOffset,
      int html_urlOffset,
      int descriptionOffset) {
    builder.startObject(6);
    Repo.addId(builder, id);
    Repo.addDescription(builder, descriptionOffset);
    Repo.addHtmlUrl(builder, html_urlOffset);
    Repo.addOwner(builder, ownerOffset);
    Repo.addFullName(builder, full_nameOffset);
    Repo.addName(builder, nameOffset);
    return Repo.endRepo(builder);
  }

  public static void startRepo(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addFullName(FlatBufferBuilder builder, int fullNameOffset) { builder.addOffset(2, fullNameOffset, 0); }
  public static void addOwner(FlatBufferBuilder builder, int ownerOffset) { builder.addOffset(3, ownerOffset, 0); }
  public static void addHtmlUrl(FlatBufferBuilder builder, int htmlUrlOffset) { builder.addOffset(4, htmlUrlOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(5, descriptionOffset, 0); }
  public static int endRepo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

