// automatically generated by the FlatBuffers compiler, do not modify

package io.flatbutterx.sample;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;
import io.flatbufferx.core.FlatBufferSrc;

@SuppressWarnings("unused")
@FlatBufferSrc
public final class User extends Table {
  public static User getRootAsUser(ByteBuffer _bb) { return getRootAsUser(_bb, new User()); }
  public static User getRootAsUser(ByteBuffer _bb, User obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public User __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String login() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer loginAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer loginInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long id() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createUser(FlatBufferBuilder builder,
      int loginOffset,
      long id) {
    builder.startObject(2);
    User.addId(builder, id);
    User.addLogin(builder, loginOffset);
    return User.endUser(builder);
  }

  public static void startUser(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addLogin(FlatBufferBuilder builder, int loginOffset) { builder.addOffset(0, loginOffset, 0); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(1, id, 0L); }
  public static int endUser(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

